[[main]]
  name = "Home"
  url = ""
  weight = -110

[[main]]
  name = "Series"
  identifier = "Series"
  weight = -107
[[main]]
  parent ="Series"
  name = "Termux"
  url = "https://www.uptech.cf/series/termux/"
[[main]]
  parent = "Series"
  name = "Web-Security"
  url = "https://www.uptech.cf/series/web-security/"

[[main]]
  name = "Contact"
  url = "https://www.uptech.cf/contact/"
  weight = -109

[[main]]
  name = "Downloads"
  url = "https://www.uptech.cf/downloads"
  weight = -108 

# Submenus are done this way: parent -> identifier
#[[main]]
  #name = "Links"
  #identifier = "Links"
 # weight = -108
#[[main]]
  #parent = "Links"
  #name = "LinkedIn"
  #url = "https://www.linkedin.com/"
#[[main]]
 # parent = "Links"
  #name = "Twitter"
  #url = "https://twitter.com/"
 #[[main]]
 # parent = "Links"
  #name = "Facebook"
  #url = "https://facebook.com/"


#[[main]]
 # name = "About"
 # url = "about/"
  #weight = -107